server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: nk-order-process-ms
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
    url: /docs/openapi.yaml